FROM container.repository.cloudera.com/cloudera/flink-extended:1.20.1-csaop1.5.0-b275
USER root
COPY iceberg-flink-runtime-1.20-1.7.2.jar /opt/flink/lib/
COPY iceberg-aws-bundle-1.7.2.jar /opt/flink/lib/
COPY flink-shaded-hadoop-2-uber-2.8.3-10.0.jar /opt/flink/lib/
RUN chmod 644 /opt/flink/lib/iceberg-*.jar /opt/flink/lib/flink-shaded-hadoop-2-uber-*.jar
USER 9999
